
export const userActions = {
    LOGOUT_USER : "user/LOGOUT",
};

export const mealActions = {
    SET_TITLE : "meal/SET_TITLE",
    UPDATE_INGREDIENTS : "meal/UPDATE_INGREDIENTS",
    RESET_CURRENT_MEAL : "meal/RESET_CURRENT_MEAL",
    CREATE_NEW_MEAL: "meal/CREATE_NEW_MEAL",
    SET_CURRENT_MEAL : "meal/SET_CURRENT_MEAL"
};

export const ingredientActions = {
    SET_CURRENT_INGREDIENT : "ingredient/SET_INGREDIENT",
    SET_INGREDIENT_QUANTITY: "ingredient/SET_INGREDIENT_QUANTITY",
    RESET_CURRENT_INGREDIENT : "ingredient/RESET_CURRENT_INGREDIENT"
};

export const mealCategoryActions = {
    SET_MEAL_CATEGORY_DESCRIPTION : "mealCategory/SET_MEAL_CATEGORY_DESCRIPTION",
    SET_MEAL_CATEGORY_PRIORITY : "mealCategory/SET_MEAL_CATEGORY_PRIORITY",
    SET_CURRENT_CATEGORY : "mealCategory/SET_CURRENT_CATEGORY",
    RESET_CURRENT_CATEGORY : "mealCategory/RESET_CURRENT_CATEGORY",
};

export const nutritionActions = {
    SET_CURRENT_MEAL : "SET_CURRENT_MEAL",
    ADD_ALTERNATIVE : "ADD_ALTERNATIVE_TO_CURRENT_MEAL",
    SET_CURRENT_INGREDIENT : "SET_CURRENT_INGREDIENT",
    SET_INGREDIENT_QUANTITY : "SET_INGREDIENT_QUANTITY",
    CREATE_MEAL : "CREATE_MEAL",
    SET_CONSTRUCTED_MEAL : "SET_CONSTRUCTED_MEAL",
}