
export const userActions = {
    REGISTER_NEW_USER : "user/REGISTER_NEW_USER",
    LOGOUT_USER : "user/LOGOUT",
    CREATE_MEAL_PLAN : "user/CREATE_MEAL_PLAN",
    SET_MEAL_PLAN : "user/SET_MEAL_PLAN",
}

export const authActions = {
    REGISTER_NEW_USER : "user/REGISTER_NEW_USER",
    CREATE_MEAL_PLAN : "user/CREATE_MEAL_PLAN"
}

export const mealActions = {
    ADD_INGREDIENT : "meal/ADD_INGREDIENT",
    SET_TITLE : "meal/SET_LABEL",
    REMOVE_INGREDIENT : "meal/REMOVE_INGREDIENT",
    RESET_CURRENT_MEAL : "meal/RESET_CURRENT_MEAL"
};

export const ingredientActions = {
    SET_CURRENT_INGREDIENT : "ingredient/SET_INGREDIENT",
    SET_INGREDIENT_QUANTITY: "ingredient/SET_INGREDIENT_QUANTITY",
    RESET_CURRENT_INGREDIENT : "ingredient/RESET_CURRENT_INGREDIENT"
};

export const mealCategoryActions = {
    SET_MEAL_CATEGORY_DESCRIPTION : "mealCategory/SET_MEAL_CATEGORY_DESCRIPTION",
    ADD_MEAL_TO_CATEGORY : "mealCategory/ADD_MEAL_TO_CATEGORY",
    REMOVE_MEAL_FROM_CATEGORY : "mealCategory/REMOVE_MEAL_FROM_CATEGORY",
    SET_CURRENT_CATEGORY : "mealCategory/SET_CURRENT_CATEGORY",
    RESET_CURRENT_CATEGORY : "mealCategory/RESET_CURRENT_CATEGORY",
    CREATE_MEAL_CATEGORY : "mealCategory/RESET_CURRENT_CATEGORY"
};

export const nutritionActions = {
    SET_CURRENT_MEAL : "SET_CURRENT_MEAL",
    SET_CURRENT_ALTERNATIVE : "SET_CURRENT_ALTERNATIVE",
    ADD_ALTERNATIVE : "ADD_ALTERNATIVE_TO_CURRENT_MEAL",
    SET_CURRENT_INGREDIENT : "SET_CURRENT_INGREDIENT",
    SET_INGREDIENT_QUANTITY : "SET_INGREDIENT_QUANTITY",
    CREATE_MEAL : "CREATE_MEAL",
    SET_CONSTRUCTED_MEAL : "SET_CONSTRUCTED_MEAL",

}