
export const userActions = {
    REGISTER_NEW_USER : "user/REGISTER_NEW_USER",
    LOGOUT_USER : "user/LOGOUT",
    CREATE_MEAL_PLAN : "user/CREATE_MEAL_PLAN",
    SET_MEAL_PLAN : "user/SET_MEAL_PLAN",
}

export const authActions = {
    REGISTER_NEW_USER : "user/REGISTER_NEW_USER",
    CREATE_MEAL_PLAN : "user/CREATE_MEAL_PLAN"
}

export const nutritionActions = {
    SET_CURRENT_MEAL : "SET_CURRENT_MEAL",
    SET_CURRENT_ALTERNATIVE : "SET_CURRENT_ALTERNATIVE",
    ADD_ALTERNATIVE : "ADD_ALTERNATIVE_TO_CURRENT_MEAL",
    SET_CURRENT_INGREDIENT : "SET_CURRENT_INGREDIENT",
    SET_INGREDIENT_QUANTITY : "SET_INGREDIENT_QUANTITY",
    CREATE_MEAL : "CREATE_MEAL",
    SET_CONSTRUCTED_MEAL : "SET_CONSTRUCTED_MEAL",

}